const generateReadme = (answers) => {
    return `
    
<h1 align='center'>${answers.Title}</h1>
![badge](https://img.shields.io/badge/license-${answers.license}-yellow)

## Description

>🔍 ${answers.Description}

## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Contact](#contact)

## Installation

>💾 ${answers.Installation}

## Usage

>💻 ${answers.Usage}

## License

![badge](https://img.shields.io/badge/license-${answers.License}-yellow)

>This application is covered by ${answers.License} license.

## Contributing

>👨‍💻 ${answers.Contributing}

## Tests

>🧪 ${answers.Tests}

## Contact

>Find me on GitHub: [${answers.Username}](https://github.com/${answers.Username})
>
>✉️ Or email me with any questions at ${answers.Email}.

<br></br>
_This README was generated by [README-Generator](https://github.com/tobin14-jpg/README-Generator)_
`
}

module.exports = generateReadme;

